name: Scheduled Twitter Bot

on:
  schedule:
    # Runs 6 times per day (every 4 hours)
    - cron: '0 */4 * * *'
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Setup data directory
      run: |
        mkdir -p data
        if [ ! -f data/posts_tweeted.json ]; then
          cp templates/posts_tweeted_template.json data/posts_tweeted.json
        fi
        
    - name: Run script
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        X_API_KEY: ${{ secrets.X_API_KEY }}
        X_API_KEY_SECRET: ${{ secrets.X_API_KEY_SECRET }}
        X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
        X_ACCESS_TOKEN_SECRET: ${{ secrets.X_ACCESS_TOKEN_SECRET }}
        X_BEARER_TOKEN: ${{ secrets.X_BEARER_TOKEN }}
        X_CLIENT_ID: ${{ secrets.X_CLIENT_ID }}
        X_CLIENT_SECRET: ${{ secrets.X_CLIENT_SECRET }}
      run: |
        python main.py 