name: Scheduled Twitter Bot

on:
  schedule:
    # Runs 4 times per day (every 6 hours)
    - cron: '0 */6 * * *'
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run script
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        WEIBO_USERNAME: ${{ secrets.WEIBO_USERNAME }}
        WEIBO_PASSWORD: ${{ secrets.WEIBO_PASSWORD }}
      run: |
        python main.py 