name: Scheduled Twitter Bot

on:
  schedule:
    # Runs 6 times per day (every 4 hours)
    - cron: '0 */4 * * *'
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  run-script:
    runs-on: ubuntu-latest
    # Add permission to push
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run script
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        X_API_KEY: ${{ secrets.X_API_KEY }}
        X_API_KEY_SECRET: ${{ secrets.X_API_KEY_SECRET }}
        X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
        X_ACCESS_TOKEN_SECRET: ${{ secrets.X_ACCESS_TOKEN_SECRET }}
        X_BEARER_TOKEN: ${{ secrets.X_BEARER_TOKEN }}
        X_CLIENT_ID: ${{ secrets.X_CLIENT_ID }}
        X_CLIENT_SECRET: ${{ secrets.X_CLIENT_SECRET }}
      run: |
        python main.py

    - name: Commit and push if changed
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git pull origin main --rebase  # Pull and rebase any remote changes
        git add data/posts_tweeted.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update posts tracking" && git push) 